version: '3.8'

x-podman:
  in_pod: false
  userns_mode: keep-id

services:
  sconce:
    #build: .
    image: ghcr.io/geraveoyomama/sconce:latest
    container_name: sconce
    restart: unless-stopped
    #userns_mode: keep-id
    volumes:
      - ./torch-server:/app/torch-server
      #- ./entrypoint.sh:/root/entrypoint.sh #uncomment to inject custom entrypoint without rebuilding. ONLY IF YOU KNOW WHAT YOU ARE DOING!
    ports:
     - "27016:27016/udp" #Main game port.
     - "5009:5900" #change port if already in use.
     - "6080:6080" #noVNC port for clientless interaction.
     - "8080:8080"
    environment:
      - VNCPASSWORD=
      - WINEDEBUG=-all #disable wine barfing logs to terminal
#      - WINEDEBUG=+esync
      - WINEESYNC=1 #comment to disable ESYNC
      - DXVK_ASYNC=1 #should unhook the GUI from main game thread. No performance loss, only possible gains. Disable if GUI doesn't render or misbehaves.
      - WINEPARAMS= #additional parameters passed AFTER wine command (wine $WINEPARAMS %command%)
#      - TORCHFLAGS=-autostart #torch flags. Uncomment to autostart torch
