#! /bin/sh

if [ ! -f ./torch-server.zip ]; then
  wget https://build.torchapi.com/job/Torch/job/master/lastSuccessfulBuild/artifact/bin/torch-server.zip
fi

if [ ! -d ./torch-server ]; then
  unzip -d torch-server torch-server.zip 
fi


#if [ "$(stat -c '%u' torch-server)" != "1000" ]; then
#    echo "Setting owner of torch-server to UID 1000"
#    sudo chown -R 1000:1000 torch-server
#fi

podman-compose up -d && podman-compose logs -f
