name: Build and Run Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: docker
#    container
    steps:
#    - name: Download Dockerfile from external repository
#      run: |
#        curl -LJO https://raw.githubusercontent.com/external/repo/main/path/to/dockerfile
#      working-directory: path/to/your/dockerfile/directory

    - name: Build Docker image
      run: |
        docker build -t git.s8n.nl/test/idiot Containerfile
