name: Build and Run Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: podman
    steps:
    - name: cleaning podman environment
      run: podman system reset -f && rm /etc/containers/storage.conf && podman system reset -f

    - name: Use Node.js
      run: dnf install -y node git

    - name: Check out repository code
      uses: actions/checkout@v4

    - name: List files in the repository
      run: ls ${{ github.workspace }}

    - name: login container registry
      run: podman login -u geraveoyomama -p ${{ secrets.PAT_GITHUB }} ghcr.io

    - name: Build Docker image
      run: buildah build -t ghcr.io/geraveoyomama/sconce:test .

    - name: Push container image
      run: podman push ghcr.io/geraveoyomama/sconce:test
