name: Build and Run Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: podman
#    container
    steps:
#    - name: Download Dockerfile from external repository
#      run: |
#        curl -LJO https://raw.githubusercontent.com/external/repo/main/path/to/dockerfile
#      working-directory: path/to/your/dockerfile/directory
    - name: cleaning podman environment
      run: podman system reset -f && rm /etc/containers/storage.conf && podman system reset -f
    - name: test ID
      run: id
#    - name: list fuse dev
#      run: ls -la /dev/fuse
    - name: Use Node.js
      run: dnf install -y node git
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - name: Build Docker image
      run: |
        buildah build -t simple .
