name: Build and sconce image

on:
  push:
    branches:
      - sid

jobs:
  build-and-run:
    runs-on: s8n-runner
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Login s8n container registry
      run: podman login -u geraveoyomama -p ${{ secrets.FORGEJO_LOGIN_PASSWORD }} git.s8n.nl

    - name: Build Docker image
      run: buildah build -t git.s8n.nl/geraveoyomama/sconce:sid .

    - name: Push container image to git.s8n.nl
      run: podman push git.s8n.nl/geraveoyomama/sconce:sid
