name: Build and Run Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: s8n-runner
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: login container registry
      run: podman --log-level debug login -u geraveoyomama -p ${{ secrets.PAT_GITHUB }} ghcr.io

    - name: Build Docker image
      run: buildah build -t ghcr.io/geraveoyomama/sconce:latest -t git.s8n.nl/geraveoyomama/sconce:latest .

    - name: Push container image
      run: podman push ghcr.io/geraveoyomama/sconce:latest git.s8n.nl/geraveoyomama/sconce:latest
